"""
tests/test_golden_files_multi.py — golden-file regression testing for
Tool 2's unified documentation, against the real multi-workflow fixtures
under tests/fixtures/multi/ (see tests/fixtures/multi/SOURCES.md for
provenance).

Mirrors tests/test_golden_files.py's contract exactly: committed expected
output lives in tests/golden/multi/, regenerated the same way
document_repository() does (via tool2.multi_pipeline._build_documentation,
always with use_llm=False so no non-deterministic LLM prose ever enters a
committed golden file), and diffed against the committed copy. Golden
files are never regenerated by this test or any other automated process —
to intentionally update them, run:

    python scripts/update_golden_files_multi.py

then inspect the diff and commit the result.

In addition to the exact-match regression check every repo gets, `black`
(the one fixture with a genuine cross-file `workflow_run` relationship)
gets two extra assertions specific to Phase 6's core architectural fix:
the `LINKED WORKFLOWS` section actually names the relationship, and the
generated Mermaid diagram has no cross-file trigger->job edge — the
real-data proof that the origin-scoped trigger-wiring fix
(`ir.schema.Trigger.origin`/`Job.origin`,
`generators.mermaid_generator.generate_mermaid`'s scoped wiring loop)
works, not just against the synthetic pipelines in
tests/test_multi_pipeline.py.
"""

import difflib
import os

import pytest

from tool2.multi_pipeline import _build_documentation

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "golden", "multi")

REAL_MULTI_FIXTURE_REPOS = ["black", "tox", "starlette"]


def _generate_fresh(repo):
    # Same portable-relative-path reasoning as test_golden_files.py: chdir
    # scoped to this block, always restored, so the freshly generated
    # "Source:" line matches the portable path committed in the golden file.
    original_cwd = os.getcwd()
    os.chdir(REPO_ROOT)
    try:
        return _build_documentation(os.path.join("tests", "fixtures", "multi", repo), use_llm=False)
    finally:
        os.chdir(original_cwd)


@pytest.mark.parametrize("repo", REAL_MULTI_FIXTURE_REPOS)
def test_generated_documentation_matches_golden_file(repo):
    golden_path = os.path.join(GOLDEN_DIR, f"{repo}.md")
    fresh = _generate_fresh(repo)

    with open(golden_path, encoding="utf-8") as f:
        golden = f.read()

    if fresh != golden:
        diff = "".join(difflib.unified_diff(
            golden.splitlines(keepends=True),
            fresh.splitlines(keepends=True),
            fromfile=f"tests/golden/multi/{repo}.md (committed)",
            tofile=f"{repo} (freshly generated)",
        ))
        pytest.fail(
            f"Generated documentation for tests/fixtures/multi/{repo} no longer "
            f"matches the committed golden file tests/golden/multi/{repo}.md.\n\n"
            f"{diff}\n"
            "If this change is intentional, run "
            "`python scripts/update_golden_files_multi.py` and commit the result."
        )


def test_golden_files_contain_no_llm_overview_block():
    """use_llm=False must hold for every committed multi-pipeline golden
    file — no non-deterministic LLM prose ever committed as ground truth."""
    for repo in REAL_MULTI_FIXTURE_REPOS:
        golden_path = os.path.join(GOLDEN_DIR, f"{repo}.md")
        content = open(golden_path, encoding="utf-8").read()
        assert "<!-- llm-overview:start -->" not in content, repo


def test_black_linked_workflows_section_names_the_relationship():
    fresh = _generate_fresh("black")
    assert "LINKED WORKFLOWS" in fresh
    assert "triggered_by diff-shades" in fresh


def test_black_mermaid_has_no_cross_file_trigger_edge():
    """The real-data proof of Phase 6's origin-scoping fix: the
    workflow_run trigger (belonging to diff_shades_comment.yml) must wire
    only to that file's own job, never to a diff_shades.yml or lint.yml
    job, and vice versa."""
    fresh = _generate_fresh("black")
    mermaid_start = fresh.index("```mermaid\n") + len("```mermaid\n")
    mermaid_end = fresh.index("```\n", mermaid_start)
    mermaid = fresh[mermaid_start:mermaid_end]

    assert "trigger_2 --> diff_shades_comment_yml__comment" in mermaid
    for job in (
        "diff_shades_yml__configure",
        "diff_shades_yml__analysis-base",
        "diff_shades_yml__analysis-target",
        "diff_shades_yml__compare",
        "lint_yml__lint",
    ):
        assert f"trigger_2 --> {job}" not in mermaid
