"""
tests/test_golden_files.py — golden-file regression testing for Tool 1's
generated documentation (EVALUATION_PLAN.md Tier 1, method 1).

Committed expected output for all 10 real fixtures lives in tests/golden/.
This test regenerates fresh output the same way document_pipeline() does
(parse via GitHubActionsParser, then generate_documentation()) and diffs
it against the committed copy — any drift in the parser or either
generator's output fails the build, distinct from the mermaid-cli
rendering check in tests/test_single_pipeline.py.

Golden files are never regenerated by this test or any other automated
process. To intentionally update them after a real output change, run:

    python scripts/update_golden_files.py

then inspect the diff and commit the result.
"""

import difflib
import os

import pytest

from parsers.github_actions import GitHubActionsParser
from tool1.single_pipeline import generate_documentation

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "golden")

REAL_FIXTURE_FILES = [
    "checkout_check_dist.yml",
    "eslint_ci.yml",
    "fastapi_test.yml",
    "flask_tests.yml",
    "node_test_linux.yml",
    "pandas_unit_tests.yml",
    "pytorch_lint.yml",
    "rust_ci.yml",
    "setup_python_test.yml",
    "upload_artifact_test.yml",
]


@pytest.mark.parametrize("filename", REAL_FIXTURE_FILES)
def test_generated_documentation_matches_golden_file(filename):
    stem = filename.rsplit(".", 1)[0]
    golden_path = os.path.join(GOLDEN_DIR, f"{stem}.md")

    # Parse with a repo-root-relative path (chdir scoped to this block,
    # always restored) so the freshly generated "Source:" line matches the
    # portable "tests/fixtures/<file>.yml" committed in the golden file,
    # regardless of the invoker's absolute checkout path or cwd.
    original_cwd = os.getcwd()
    os.chdir(REPO_ROOT)
    try:
        fresh = generate_documentation(
            GitHubActionsParser().parse(os.path.join("tests", "fixtures", filename))
        )
    finally:
        os.chdir(original_cwd)

    with open(golden_path, encoding="utf-8") as f:
        golden = f.read()

    if fresh != golden:
        diff = "".join(difflib.unified_diff(
            golden.splitlines(keepends=True),
            fresh.splitlines(keepends=True),
            fromfile=f"tests/golden/{stem}.md (committed)",
            tofile=f"{filename} (freshly generated)",
        ))
        pytest.fail(
            f"Generated documentation for {filename} no longer matches the "
            f"committed golden file tests/golden/{stem}.md.\n\n"
            f"{diff}\n"
            "If this change is intentional, run "
            "`python scripts/update_golden_files.py` and commit the result."
        )
